$cfg = @'
baseURL = "https://beeplanetconnection.org/"
title  = "Bee Planet Connection"
languageCode = "en-us"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.highlight]
    noClasses = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']

[outputs]
home    = ["HTML","RSS"]
page    = ["HTML"]
section = ["HTML","RSS"]
'@

$enc = [Text.UTF8Encoding]::new($false)   # UTF-8 no BOM
[IO.File]::WriteAllText(".\site\config.toml", $cfg, $enc)
