baseURL = "https://beeplanetconnection.org/"
title  = "Bee Planet Connection"
languageCode = "en-us"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.highlight]
    noClasses = true




  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
ignoreLogs = ['warning-goldmark-raw-html']