baseURL = "https://beeplanetconnection.org/"
title  = "Bee Planet Connection"
languageCode = "en-us"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.highlight]
    noClasses = true



